USE_CAMERA_STUB := true

# inherit from the proprietary version
#-include vendor/rockchip/rk30sdk/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := rk3368
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := arm64-v8a,armeabi-v7a,armeabi
TARGET_ARCH_ABILIST32 := armeabi-v7a,armeabi
TARGET_ARCH_ABILIST64 := arm64-v8a
TARGET_ARCH_VARIANT := arm64-v8a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a53
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := rk30sdk

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x60400000
BOARD_KERNEL_PAGESIZE := 16384

# fix this up by examining /proc/mtd on a running device
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00010000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00018000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x00400000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x3B70000
BOARD_FLASH_BLOCK_SIZE := 512

TARGET_PREBUILT_KERNEL := device/rockchip/rk30sdk/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
